#! /bin/bash

### BEGIN INIT INFO
# Provides:          fancontrol.py
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Carry out specific functions when asked to by the system
#env > /home/pi/Desktop/env.txt
case "$1" in
  start)
    echo "Starting fancontroller.py"
    sudo -u pi /usr/local/projects/RPiCpuFanControl/fanController.py &
    ;;
  stop)
    echo "Stopping fancontroller.py"
    pkill -f /usr/local/projects/RPiCpuFanControl/fanController.py
    ;;
  *)
    echo "Usage: /etc/init.d/fancontrol {start|stop}"
    exit 1
    ;;
esac

exit 0